# Generated by Django 3.2.4 on 2021-06-21 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingInvitees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('GOING', 'Going'), ('NOT GOING', 'Going'), ('MAY BE', 'Going')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('room_number', models.AutoField(primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('title', models.CharField(default='Title', max_length=100)),
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reserved_from', models.DateTimeField()),
                ('reserved_to', models.DateTimeField()),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CANCELLED', 'Cancelled')], default='RESERVED', max_length=20)),
                ('invitees', models.ManyToManyField(related_name='reservation_invitees', through='core.MeetingInvitees', to=settings.AUTH_USER_MODEL)),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.meetingroom')),
            ],
        ),
        migrations.AddField(
            model_name='meetinginvitees',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reservation'),
        ),
        migrations.AddField(
            model_name='meetinginvitees',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
