# Generated by Django 3.2.4 on 2021-06-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinginvitees',
            name='response',
            field=models.CharField(choices=[('GOING', 'Going'), ('NOT GOING', 'Not Going'), ('MAY BE', 'May be')], max_length=20),
        ),
    ]
